### ISSUE TITLE
Tutorial Updates

### ISSUE THREAD

**Issue by sml5527** [thinkingcapgroup/masterThinkingCap#150]
- [x] Explain the Areas and the biases associated with them as well as why the quad doesn't have events in it

- [x] Explain What a Statement Does

- [x] Mention that all of this information can be viewed from the help menu later

- [x] Bring Up that Statements require 1 hour and Actions require at least 2

- [x] Mention that polling during the day will take time, but you will be given a free poll at the start of every day and that you can take as many polls as you have time for.

- [x] Explain that Karma Mimics your Statement

Revisit language on Pages 
- [x] Polling
- [x] Statements

**Comment by ms8565** [comment]
Also how the frick frack padiwack fame/consistency/etc work
- [x] Voters hate a loosey goose
- [x] How your fame and your statements interact
