### ISSUE TITLE
Refactor Polling Controls

### ISSUE THREAD

**Issue by ms8565** [thinkingcapgroup/masterThinkingCap#151]
Redo the following stuff in the polling screen:
- [x] Give feedback or remove the button when the player has reached the maximum amount of questions
- [x] Remove option to add more questions when the player shouldn't be able to (tutorial poll, end of day poll, etc)
- [x] Have a button to remove questions rather than just setting them to "None"
- [x] Remove the "Time Spent" dropdown since it has no function
- [x] When the player doesn't have enough time to give the poll, display an error message below the questions instead of taking the player to a different screen
- [x] Highlight duplicate questions during the duplicate error handling

**Comment by sml5527** [comment]
Remove the adding questions and added the stuff above to the polling area
