### ISSUE TITLE
Helpful info blurbs

### ISSUE THREAD

**Issue by ms8565** [thinkingcapgroup/masterThinkingCap#154]
Some parts of the game need some extra explaining so that the player knows what to do
- [ ] When starting a new game, warn the player that starting a new game will overwrite their old game
- [x] When choosing a difficulty, give information about what the difficult rating affects
- [x] Explain that the tutorial poll is not real and doesn't include real candidates
- [x] During the first statement, explicitly state that the first statement must be positive
- [x] Change the event information screen to clearly say what groups are positively affected
- [x] Explain the end of the day poll with something like "You've finished the game! Poll the students to see where you stand."

**Comment by sml5527** [comment]
There's no real need to inform the player that new game will overwrite their file. The majority of participants will not be restarting the game and they will be informed of the continue button in case they are removed from the game.
