### ISSUE TITLE
THAT ONE POLL BUG

### ISSUE THREAD

**Issue by aaronjmill32** [thinkingcapgroup/masterThinkingCap#69]
tableArrays[candCounter] is undefined Poll not showing up due to error

**Comment by aaronjmill32** [comment]
Still cannot figure out what causes this issue.

**Comment by aaronjmill32** [comment]
probably the candCounter goes too high for the array/doesn't exist or somehow tableArrays doesn't exist

**Comment by sml5527** [comment]
Error: When emptying the array to hold table values it \shortened the length of the Array.
