### ISSUE TITLE
NaN Glitch

### ISSUE THREAD

**Issue by sml5527** [thinkingcapgroup/masterThinkingCap#73]
Polling Glitch results in some NaN values.
Glitch Present on Heroku and in my branch.

**Comment by sml5527** [comment]
Likely a glitch with Fame

**Comment by sml5527** [comment]
![nan glitch](https://cloud.githubusercontent.com/assets/14907108/20322064/ad877414-ab45-11e6-829e-b2b04ac16cef.png)

**Comment by aaronjmill32** [comment]
Not getting NaNs, but I'm getting unknown candidates with a score of 0

**Comment by aaronjmill32** [comment]
Turns out it was a glitch between the fakeCandidates for the tutorial and the regular candidates.

**Comment by aaronjmill32** [comment]
Seem to have it working now the numbers seem different. Might need to make a seperate pollCalc for tutorial or a seperate candidate holder for everything (might be best)
