### ISSUE TITLE
Tutorial Polling

### ISSUE THREAD

**Issue by aaronjmill32** [thinkingcapgroup/masterThinkingCap#9]
Create the tutorial for making a poll & reading a poll

**Comment by sml5527** [comment]
Tutorial Must Include
- Polling
   Maps
   Population and Sample
   Questions and Total Time
   What Data It Gives You
   Show Graph Questions At Any Time
- Actions
   Statements affect Issue Scores with targeted groups
   Events affect Fame with targeted groups
   Mini-games affected all groups based on your score.

**Comment by aaronjmill32** [comment]
Currently we've made a sandbox tutorial area, they can make a survey for the sample and see the sample data.

**Comment by sml5527** [comment]
Sandbox finished. Guide Text Needed
